spring.application.name=backend
server.port=8081

# Informacoes sobre o Banco de Dados
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/saep_agendamento_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA - criacao/atualizacao automatica das tabelas durante o desenvolvimento
spring.jpa.hibernate.ddl-auto=update
# Mostra o SQL no terminal durante o desenvolvimento
spring.jpa.show-sql=true
# Formata o SQL exibido no terminal
spring.jpa.properties.hibernate.format_sql=true
# Mantem o acesso ao banco restrito a transacoes da camada de servico
spring.jpa.open-in-view=false
# Dialeto especifico do PostgreSQL
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
